// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbuhmjjfhymsofudiyiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidWhtampmaHltc29mdWRpeWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzcyMzEsImV4cCI6MjA3NDMxMzIzMX0.PytIwBkd5hotiw8CJlkx4R59fl6jFnJtIe9T80P96VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});